# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - id: "bird_qq_bot"
    main: ./
    binary: "bird_qq_bot"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
  - id: "webserver"
    main: ./sidecar/webserver
    binary: "webserver"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format: binary # 不打包成 tar.gz，直接上传二进制文件
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  extra_files:
    - glob: "application.example.yaml"
    - glob: "DingTalk JinBuTi.ttf"
