bot:
  account: 123456789 # bot QQ号
  password: 123456789 # bot QQ密码

# 模块全局配置
module:
  # 是否根据配置文件启用模块，与 app.go 中的 import _ 是 「逻辑与」关系
  # 即，如果为 true，需要 import _ 和 模块的 enable 值同为 true 的时候，才生效
  enableByConfig: true
  # 是否启用各个子模块，当 enableByConfig 为 true 时，此值才生效
  enable:
    internal.logging: true  # 日志模块，必须开启
    bird.loveMsg: true      # 情话模块
    bird.noCopy: true       # 防复读
    bird.autoCopy: true     # 自动复读
    bird.pong: true         # 存活确认模块
    bird.takeOut: true      # 外卖模块，包含roll点与随机@
    bird.randAt: true       # 随机@模块
    # 以下模块是我服务器的专属功能，不建议开启
    bird.restart: false     # 重启模块
    bird.tianXing: false   # 天行api模块，需要申请 apiKey，见模块详细配置
    bird.kaoyanScore: true  # 考研分数统计模块

# 子模块个性化配置
modules:
  internal.logging:   # 日志模块
  bird.loveMsg:       # 情话模块
    triggers: ["宝贝"]
  bird.noCopy:        # 防复读
    # 防复读白名单，应当加入所有指令
    whiteListWord: ["外卖", "宝贝", "嗯嗯", "开枪", "晚安"]
    banGroups: [123456789] # 关闭防复读的群
    whiteListQQ: [123456789]    # 不受防复读限制的QQ号
  bird.autoCopy:        # 自动复读
    allowGroups: [123456789] # 开启自动复读的群
  bird.pong:          # 存活确认模块
    triggers: ["#ping"]
    allows:
      - 123456789
  bird.takeOut:       # 外卖模块
    triggers: ["外卖"]
  bird.restart:       # 重启模块
    triggers: ["#重启"]
    webhook:
    allows:
      - 123456789
  bird.tianXing:     # 天行api模块
    apiKey: xxxxxxxxxxx # https://www.tianapi.com/apiview/142 需要申请 apiKey
    triggers:
      morning: ["早安"] # 早安
      night: ["晚安"]  # 晚安
      dog: ["舔狗日记"] # 舔狗日记
      healthTip: ["健康小贴士"] #健康小贴士
  bird.randAt: # 随机@模块
    triggers: ["开枪", "随机@"]
  bird.kaoyanScore: # 考研分数统计模块
    triggers: ["分数实时排名"]  # 主动触发排名计算，只有管理可以触发
    allowGroupList: # 允许计算的群列表
      - 123456789
    tailMsg: "祝大家复试顺利！" # 自定义尾部消息
