bot:
  account: 123456789 # bot QQ号
  password: 123456789 # bot QQ密码

# 模块全局配置
module:
  # 是否根据配置文件启用模块，与 app.go 中的 import _ 是 「逻辑与」关系
  # 即，如果为 true，需要 import _ 和 模块的 enable 值同为 true 的时候，才生效
  enableByConfig: true
  # 是否启用各个子模块，当 enableByConfig 为 true 时，此值才生效
  enable:
    internal.logging: true  # 日志模块，必须开启
    bird.loveMsg: true      # 情话模块
    bird.noCopy: true       # 防复读
    bird.pong: true         # 心跳模块
    bird.takeOut: true      # 外卖模块，包含roll点与随机@
    bird.randAt: true       # 随机@模块
    # 以下模块是我服务器的专属功能，不建议开启
    bird.restart: false     # 重启模块
    bird.goodNight: false   # 晚安模块，需要申请 apiKey，见模块详细配置

# 子模块个性化配置
modules:
  internal.logging:   # 日志模块
  bird.loveMsg:       # 情话模块
    triggers:
      - "宝贝"
  bird.noCopy:        # 防复读
    whiteListWord: # 防复读白名单，应当加入所有指令
      - "外卖"
      - "宝贝"
      - "嗯嗯"
      - "开枪"
      - "晚安"
  bird.pong:          # 心跳模块
    triggers:
      - "#ping"
    allows:
      - 123456789
  bird.takeOut:       # 外卖模块
    triggers:
      - "外卖"
  bird.restart:       # 重启模块
    triggers:
      - "#重启"
    webhook:
    allows:
      - 123456789
  bird.goodNight:     # 晚安模块
    triggers:
      - "晚安"
    apiKey: xxxxxxxxxxx # https://www.tianapi.com/apiview/142 需要申请 apiKey
  bird.randAt: # 随机@模块
    triggers:
      - "开枪"
      - "随机@"
